[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jbright"
dependencies = []
dynamic = ["version"]

[project.scripts]
jbright = "jbright.cli:main"

[tool.setuptools.packages.find]
where = ["."]
