#!/usr/bin/env bash

declare -a autoPatchelfLibs
declare -a extraAutoPatchelfLibs
declare -a runtimeDependenciesArray

addEnvHooks() {
    # We don't need to do anything here, we just need this function to exist
    # for setup-hook to run without crashing.
    :
}

# shellcheck disable=SC2034
# (autoPatchelfIgnoreMissingDeps is used by the setup-hook we're sourcing)
autoPatchelfIgnoreMissingDeps=(libopenblasp-r0-9f9f5dbc.3.18.so)

# shellcheck source=/dev/null
source "$(nix build --no-link --print-out-paths nixpkgs#autoPatchelfHook)/nix-support/setup-hook"

# Add more libraries here as needed.
addAutoPatchelfSearchPath "$(nix build --no-link --print-out-paths 'nixpkgs#gcc11Stdenv.cc.cc.lib')/lib"
addAutoPatchelfSearchPath "$(nix build --no-link --print-out-paths 'nixpkgs#zlib')/lib"
addAutoPatchelfSearchPath "$(nix build --no-link --print-out-paths 'nixpkgs#fontconfig.lib')/lib" # added for npm-installed phantomjs-prebuilt
# addAutoPatchelfSearchPath "$(nix build --no-link --print-out-paths 'nixpkgs#openssl.out')/lib"

echo "Debugging info from sd nix patch:"
echo "autoPatchelfLibs: ${autoPatchelfLibs[*]}"
echo "extraAutoPatchelfLibs: ${extraAutoPatchelfLibs[*]}"
echo "runtimeDependenciesArray: ${runtimeDependenciesArray[*]}"

autoPatchelf -- "${1:-.}"
