[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "imap-strip-attachments"
dependencies = []
dynamic = ["version"]

[project.scripts]
imap-strip-attachments = "imap_strip_attachments.main:main"

[tool.setuptools.packages.find]
where = ["."]
