kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      hostname: transmission
      volumes:
      - name: mnt-media
        hostPath:
          path: /mnt/media
      containers:
        - name: transmission
          image: containers.clark.snowdon.jflei.com/transmission:latest
          ports:
            - containerPort: 61207
          volumeMounts:
            - name: mnt-media
              mountPath: /mnt/media

---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: vpn

spec:
  ports:
    - name: http
      port: 80
      targetPort: 9091
  selector:
    app: transmission
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: torrents
  namespace: vpn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-snowauth@kubernetescrd
spec:
  tls:
    - hosts:
      - torrents.clark.snowdon.jflei.com
      secretName: torrents-tls
  rules:
  - host: torrents.clark.snowdon.jflei.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: transmission
              port:
                number: 80
