#!/usr/bin/env bash

set -euo pipefail

function main() {
    HDMI1_STATUS=$(</sys/class/drm/card0/card0-HDMI-A-1/status)
    DP1_STATUS=$(</sys/class/drm/card0/card0-DP-1/status)
    DP2_STATUS=$(</sys/class/drm/card0/card0-DP-2/status)

    if [ "$HDMI1_STATUS" == "connected" ]; then
        LAYOUT_NAME=hdmi
        DPI=96

        xrandr --output HDMI1 --preferred --pos 0x0 --rotate normal --output VIRTUAL1 --off --output DP1 --off --output eDP1 --off --output DP2 --off
    elif [ "$DP1_STATUS" == "connected" ]; then
        LAYOUT_NAME=dp1
        DPI=96

        xrandr --output DP1 --preferred --pos 0x0 --rotate normal --output VIRTUAL1 --off --output HDMI1 --off --output eDP1 --off --output DP2 --off
    elif [ "$DP2_STATUS" == "connected" ]; then
        LAYOUT_NAME=dp4
        DPI=96

        xrandr --output DP1-2 --preferred --pos 0x0 --rotate normal --output VIRTUAL1 --off --output HDMI1 --off --output eDP1 --off --output DP2 --off
    else
        LAYOUT_NAME=mobile
        if [ "$(hostname)" = "dallben" ]; then
            DPI=133
        elif [ "$(hostname)" = "pattern" ]; then
            DPI=96
        else
            echo "Unrecognized host: $(hostname)"
            exit 1
        fi

        xrandr --output HDMI1 --off --output VIRTUAL1 --off --output DP1 --off --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP2 --off
    fi

    setbg

    # Change DPI and notify everyone via XSETTINGS.
    # See https://utcc.utoronto.ca/~cks/space/blog/linux/XSettingsNotes?showcomments
    # and https://github.com/GNOME/gtk/blob/1a1373779f87ce928a45a9371512d207445f615f/gdk/x11/xsettings-client.c#L399
    echo "Xft/DPI $((1024 * DPI))" >~/.xsettingsd
    killall -HUP xsettingsd
    # Notify alacritty about the font size change, because alacritty doesn't understand the
    # XSETTINGS protocol yet =( See
    # https://github.com/alacritty/alacritty/issues/2886 for details. size 8
    # looks decent on a 96 DPI monitor, and 11 looks pretty decent on a 133 DPI
    # monitor.
    local font_size
    font_size=$(echo "rate=(11 - 8) / (133.0 - 96.0 ); 8 + ($DPI - 96) * rate" | bc -l)
    with-alacritty set global font.size "$font_size"

    # notify-send blocks until something receives the message. When booting,
    # we have not started dunst yet, so we need to run notify-send in the background.
    notify-send "Detected environment $LAYOUT_NAME" &
}

# There's no way it's good to be running this command simultaneously.
if pgrep autoperipherals | grep -v $$; then
    echo "I see an autoperipherals command already running, let's not step on its toes."
    exit 1
fi
main
