#!/usr/bin/env bash

set -euo pipefail

function main() {
    DP_3_2_STATUS=$(xrandr | grep -o 'DP-3-2 connected')

    if [ -n "$DP_3_2_STATUS" ]; then
        LAYOUT_NAME=snowdesk
        DPI=96

        xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-3-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output eDP-1 --off --output HDMI-1-1 --off --output DP-1-1 --off --output DP-1-2 --off --output DP-1-3 --off
    else
        LAYOUT_NAME=mobile
        if [ "$(hostname)" = "dallben" ]; then
            DPI=133
        elif [ "$(hostname)" = "pattern" ]; then
            DPI=133
        else
            echo "Unrecognized host: $(hostname)"
            exit 1
        fi

        xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-2.2 --off --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-1 --off --output DP-1-1 --off --output DP-1-2 --off --output DP-1-3 --off
    fi

    setbg

    # Change DPI and notify everyone via XSETTINGS.
    # See https://utcc.utoronto.ca/~cks/space/blog/linux/XSettingsNotes?showcomments
    # and https://github.com/GNOME/gtk/blob/1a1373779f87ce928a45a9371512d207445f615f/gdk/x11/xsettings-client.c#L399
    echo "Xft/DPI $((1024 * DPI))" >~/.xsettingsd
    killall -HUP xsettingsd
    # Notify alacritty about the font size change, because alacritty doesn't understand the
    # XSETTINGS protocol yet =( See
    # https://github.com/alacritty/alacritty/issues/2886 for details.
    GOOD_96_DPI_FONT_SIZE=12
    GOOD_133_DPI_FONT_SIZE=14
    local font_size
    font_size=$(echo "rate=($GOOD_133_DPI_FONT_SIZE - $GOOD_96_DPI_FONT_SIZE) / (133.0 - 96.0); $GOOD_96_DPI_FONT_SIZE + ($DPI - 96) * rate" | bc -l)
    with-alacritty set global font.size "$font_size"

    # notify-send blocks until something receives the message. When booting,
    # we have not started dunst yet, so we need to run notify-send in the background.
    notify-send "Detected environment $LAYOUT_NAME" &
}

# There's no way it's good to be running this command simultaneously.
if pgrep autoperipherals | grep -v $$; then
    echo "I see an autoperipherals command already running, let's not step on its toes."
    exit 1
fi
main || (notify-send "Error while running autoperipherals" &)
