apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  # HACK to get local dns working. This wasn't always necessary, and this
  # shouldn't be necessary. k3s runs the core-dns pod with `dnsPolicy:
  # Default` [0], which means it should inherit dns configuration from the
  # host. That doesn't seem to be happening for some reason.
  # [0]: https://github.com/k3s-io/k3s/blob/release-1.18/manifests/coredns.yaml#L158
  custom.server: |
    ec:53 {
      forward . 192.168.28.1
    }
    snow.jflei.com:53 {
      forward . 192.168.28.1
    }
