#!/usr/bin/env python

import os
import re
import sys
import subprocess
from rich import print
from textwrap import dedent

AGE_ARMOR_RE = re.compile(
    r"-----BEGIN AGE ENCRYPTED FILE-----.*?-----END AGE ENCRYPTED FILE-----",
    re.DOTALL,
)

PRIVATE_KEY_PATH = "keys/age-private-key.txt"

def decrypt(encrypted: str) -> str:
    p = subprocess.run(
        ["age", "-i", PRIVATE_KEY_PATH, "--decrypt"],
        input=encrypted,
        check=True,
        capture_output=True,
        text=True,
    )
    return p.stdout

def decrypt_file(src: str, dest: str):
    with open(src, "r") as f:
        document = f.read()

    decrypted = AGE_ARMOR_RE.sub(lambda m: decrypt(m.group(0)), document)
    with open(dest, "w") as f:
        f.write(decrypted)


def main():
    if not os.path.isfile(PRIVATE_KEY_PATH):
        print(dedent(f"""\
            [bold red]Could not find: {PRIVATE_KEY_PATH}[/bold red]

            Have you decrypted the age private key?

                age --decrypt -i ~/.ssh/id_rsa keys/age-private-key.txt.age > keys/age-private-key.txt
        """), file=sys.stderr)
        sys.exit(1)

    for root, _, files in os.walk("."):
        for file in files:
            file_noext, ext = os.path.splitext(file)
            if ext == ".aged":
                decrypt_file(
                    src=os.path.join(root, file),  # foo.nix.aged
                    dest=os.path.join(root, file_noext),  # food.nix
                )

if __name__ == "__main__":
    main()
