#!/usr/bin/env bash

set -euo pipefail
shopt -s globstar

help() {
    echo "Usage: $0 [target]

To deploy a NixOS host:

    ./deploy dallben

To deploy an OpenWrt router:

    ./deploy openwrt/strider

To deploy infra as code (Kubernetes, etc):

    ./deploy iac

Options:

    --dry-run: build, but do not apply the changes
    --show-trace: passed to any invocations of the 'nix' cli
" >/dev/stderr
}

target=""
DRY_RUN=0
FORCE=0
SHOW_TRACE=()
for i in "$@"; do
    case $i in
        --dry-run)
            DRY_RUN=1
            ;;
        --force)
            FORCE=1
            ;;
        --show-trace)
            SHOW_TRACE=("--show-trace")
            ;;
        --help | -h)
            help
            exit 0
            ;;
        --* | -*)
            echo "Unknown option $i" >/dev/stderr
            echo "" >/dev/stderr
            help
            exit 1
            ;;
        *)
            if [ -n "$target" ]; then
                echo "You must specify exactly one target" >/dev/stderr
                echo "" >/dev/stderr
                help
                exit 1

            fi
            target=$i
            ;;
    esac
done

function _nix() {
    nix "${SHOW_TRACE[@]}" "$@"
}

function build_containers() {
    [ $DRY_RUN == 1 ] && echo "--dry-run not supported for build_containers, sorry!" && exit 1

    for f in iac/k8s/**/flake.nix; do
        flake=$(dirname "$f")
        target="./${flake}#stream-docker"
        result=$(_nix build "$target" --no-link --print-out-paths)

        # Note: we're intentionally using ' here instead of " because we want
        # the $ chars to be passed as-is to `nix eval`.
        # shellcheck disable=SC2016
        immutable_image=$(_nix eval "$target" --raw --apply 'img: "${img.imageName}:${img.imageTag}"')
        # shellcheck disable=SC2016
        latest_image=$(_nix eval "$target" --raw --apply 'img: "${img.imageName}:latest"')

        fq_immutable_name=docker://containers.snow.jflei.com/$immutable_image
        fq_latest_name=docker://containers.snow.jflei.com/$latest_image

        # Only build and upload the image if it doesn't already exist remotely.
        if ! skopeo inspect "$fq_immutable_name" &>/dev/null; then
            $result | gzip --fast | skopeo --insecure-policy copy docker-archive:/dev/stdin "$fq_immutable_name"
        fi

        # Finally, tag it as the latest version.
        skopeo --insecure-policy copy --preserve-digests --quiet "$fq_immutable_name" "$fq_latest_name"

        # TODO: restart affected deployments, or (better) use immutable image tags in manifests.
    done
}

function deploy_iac() {
    [ $DRY_RUN == 1 ] && echo "--dry-run not supported for deploy_iac, sorry!" && exit 1

    for f in iac/k8s/**/*{.yaml,.yaml.secret}; do
        echo "Applying $f"
        kubectl apply -f "$f"
    done

    pulumi up --cwd pulumi --stack dev --yes
}

function deploy_nix() {
    local target="$1"
    shift

    local is_local=0
    if [ "$target" = "$(hostname)" ]; then
        is_local=1
    fi

    if [ $DRY_RUN == 1 ]; then
        echo "Building (but not deploying!) new system..."
        new_system=$(_nix build ".#nixosConfigurations.$target.config.system.build.toplevel" --print-out-paths --no-link)
        if [ $is_local == 1 ]; then
            current_system=/run/current-system
        else
            current_system=$(ssh "$target" realpath /run/current-system)
            _nix copy --from "ssh://$target" "$current_system"
        fi
        _nix store diff-closures "$current_system" "$new_system"
        exit 0
    fi

    if [ "$target" = "$(hostname)" ]; then
        nixos-rebuild switch --use-remote-sudo --flake ".#$target"
    else
        [ $DRY_RUN == 1 ] && echo "--dry-run not supported for deploy_nix for remote hosts, sorry!" && exit 1
        nixos-rebuild switch --use-remote-sudo --flake ".#$target" --target-host "$target"
    fi
}

function deploy_nix_router() {
    local target="$1"
    shift

    extra_args=()
    if [ "$DRY_RUN" == 1 ]; then
        extra_args+=("--dry-run")
    fi
    if [ "$FORCE" == 1 ]; then
        extra_args+=("--force")
    fi

    hostname=${target#openwrt/}
    (cd openwrt && _nix run '.#deploy' -- "$hostname" "${extra_args[@]}")
}

tools/deage

if [ "$target" = "iac" ]; then
    build_containers
    deploy_iac
elif [[ $target == "openwrt/"* ]]; then
    deploy_nix_router "$target"
else
    deploy_nix "$target"
fi
