#!/usr/bin/env bash

set -euo pipefail

update_nixos() {
    (
        cd packages/devShell
        uv lock
    )
    nix flake update
    clan machines update "$HOSTNAME" --build-host localhost --target-host localhost
}

fw_check() {
    # For now, I'm too nervous to actually apply these updates automatically. I
    # don't know how likely they are to break things, and I don't know if
    # they're reversable. For now, just notify people if there are any updates.
    fwupdmgr refresh --force >/dev/null
    fwupdate_count=$(fwupdmgr get-updates --json | jq '.Devices | length')
    if [ "$fwupdate_count" -gt 0 ]; then
        echo ""
        echo "###"
        echo "### Found $fwupdate_count firware updates ###"
        echo "###"
        echo "Run 'fwupdmgr get-updates' to see available updates, and 'fwupdmgr update' when you're ready to do the updates."
    fi
}

update_nixos
fw_check
