[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nm-vpn-add"
dependencies = []
dynamic = ["version"]

[project.scripts]
nm-vpn-add = "cli.nm_vpn_add:main"

[tool.setuptools.packages.find]
where = ["."]
