[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jvol"
dependencies = []
dynamic = ["version"]

[project.scripts]
jvol = "jvol.cli:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"*" = ["*.svg"]
