on:
  pull_request:
  workflow_call:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = no-url-literals
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --impure
